name: Deploy to Neocities
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          # This must be "api_key" (the command the script understands)
          api_key: ${{ secrets.NEOCITIES }} 
          cleanup: false
          dist_dir: .
