name: Deploy to Neocities
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          # Use "api_token" here (this is what the tool specifically asks for)
          api_token: ${{ secrets.NEOCITIES }} 
          cleanup: false
          dist_dir: .
